//#1 - Sort 10 schools around your house by distance:
// ANS: insertion sort

//#2 - eBay sorts listings by the current Bid amount:
// ANS: radix or counting sort

//#3 - Sort scores on ESPN
// ANS: Quick sort

//#4 - Massive database (can't fit all into memory) needs to sort through past year's user data
// ANS: Merge Sort

//#5 - Almost sorted Udemy review data needs to update and add 2 new reviews
// ANS: Insertion Sort

//#6 - Temperature Records for the past 50 years in Canada
// ANS: radix or counting Sort
// ANS: Quick sort if decimal places

//#7 - Large user name database needs to be sorted. Data is very random.
// ANS: Quick sort

//#8 - You want to teach sorting
// ANS: Bubble sort